apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: mr04z6s0c-nodejs 
  janus-idp.io/tekton: mr04z6s0c-nodejs
  backstage.io/kubernetes-id: mr04z6s0c-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mr04z6s0c-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  